name: Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  minutes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - run: pnpm install
      - run: node automation/minutes.js
        env:
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: "chore: add new minutes"
          branch: automation/update-minutes
          title: "chore: add new minutes"
          token: ${{ secrets.JPOEHNELT_WRITE }}
          add-paths: |
            public/**/*.pdf
      - name: Approve PR
        if: steps.create-pr.outputs.pull-request-number != ''
        run: h pr review "$PR_URL" --approve
        env:
          GITHUB_TOKEN: ${{ secrets.JPOEHNELT_BOT_REVIEW }}
          PR_URL: ${{ steps.create-pr.outputs.pull-request-url }}
      - name: Merge PR
        if: steps.create-pr.outputs.pull-request-number != ''
        run: gh pr merge "$PR_URL" --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.JPOEHNELT_WRITE }}
          PR_URL: ${{ steps.create-pr.outputs.pull-request-url }}